### ISSUE TITLE
1.10 / 1.11 / 1.12 TODO List

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1116]
# Terrains [1.10]

### Vanilla
- [x] Extreme Hills + variants - more like BOP Mountain Peaks, but not quite as epic
- [x] Ocean & Deep Ocean - latter deeper than the former
- [ ] ~~River & Frozen River - deeper as per #923~~
- [x] ~~Mesa Plateau + variants - more epic plateaus as per RWG Canyons with multiple levels~~
- [x] Mesa - more closely resembles Arizona/Nevada mesas, whilst allowing the plateaus to 'do their thing' better
- [x] Savanna Plateau - less epic version of the new Mesa Plateaus?
- [ ] ~~Desert + variants - something more epic?~~

### Biomes O' Plenty
- [x] Crag - more like BoP, less cartoony

**Comment by Ezoteric** [comment]
touch my desert and ill ddos you for years pinky :P

**Comment by srs-bsns** [comment]
# Biome Decoration/Surfacing [1.10]

### Vanilla
- [x] ~~Remove sugar cane from snowy biomes.~~
- [x] Re-surface vanilla Ocean & Deep Ocean to be less swirly
- [x] Re-surface Extreme Hills variants to more closely match their vanilla counterparts (in blocks used, not aesthetics)
- [x] Re-decorate Taiga variants to have more varied, Taiga-esque trees.
- [x] Make Roofed Forest less dense to allow some light to shine through, whilst keeping the overall spooky vibe
- [x] Config option for adjusting the minimum Y coord for snow layers (need to change the biome's temperature to do this properly)
- [x] Blend the transition from sand beach to stone/gravel beach so it isn't so abrupt
- [x] ~~Check for: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1159 (1.11.2+ only)~~
- [x] Roofed Forest, Jungle variants: Make the trees more sparse, possibly less wide, to reduce those biomes' lagginess.

### Biomes O' Plenty
- [x] ~~Lush Desert - should use a different surface block than hardened clay.~~ After examining BoP vs RTG, I'd just leave this for now (until 1.11/1.12)

Moved here from #1037:
- [x] Coniferous Forest
- [x] Fen
- [ ] ~~Rainforest~~
- [x] Snowy Coniferous Forest
- [ ] ~~Temperate Rainforest~~
- [ ] ~~Tropical Rainforest~~
- [x] Woodland

**Comment by srs-bsns** [comment]
# Other

- [x] Add World Customisation GUI Screen (in progress)
- [x] Remove Dim 0 restriction and allow RTG to work in other dimensions (in progress)

**Comment by kenijey** [comment]
any scheduled date? we are really excited, can't wait

**Comment by srs-bsns** [comment]
No. And there won't be a release for a while as there is much to do.

**Comment by srs-bsns** [comment]
1.11 TODOs
- [ ] Fix Woodland Mansion generation

**Comment by srs-bsns** [comment]
1.12 TODOs
- [ ] ~~Adjust tree heights for all tree types/all biomes (make trees shorter)~~ This can be done when rewriting the decorators for the new system.
- [x] ~~Fix Woodland Mansion generation~~ Will open a separate issue for this, if need be.
- [ ] ~~Set up jar signing.~~

**Comment by srs-bsns** [comment]
This collection of items has pretty much run it's course. Any remaning issues with items that weren't addressed can have new issues opened in the future, if necessary, to address them.
